name: Bug Report 🐞
description: Help improve our documentation by reporting bugs, typos, and unclear content.
title: "USWDS-Site - Bug: [YOUR TITLE]"
labels: ['Type: Bug']
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the bug
      description: Add a clear and concise description of the bug. Let us know if this bug has major or minor impact and if you have a workaround.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the bug
      description: Describe how to reproduce this issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error...
    validations:
      required: false
  - type: textarea
    id: expectation
    attributes:
      label: Expected Behavior
      description: Add a clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help provide context, if applicable.
    validations:
      required: false
  - type: textarea
    id: system
    attributes:
      label: System setup
      description: If this bug occurs only on a specific browser or device, provide your system details. Be sure to include your device, operating system, and browser (with version).
      placeholder: |
        - Device:
        - Operating system:
        - Browser and version:
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
              Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
          required: true
        - label:
            I checked the [current
              issues](https://github.com/uswds/uswds-site/issues) for
              duplicate bug reports.
          required: true
