name: NoOp

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "Dummy workflow to satisfy CodeQL"